import{test}from'node:test';import assert from'node:assert/strict';
// Execute com HEROES_API_TEST=1 e a API local ativa; cria e remove apenas registros próprios.
test('API: CRUD, isolamento, validação e proposta do agente',{skip:process.env.HEROES_API_TEST!=='1'||!process.env.HEROES_TEST_COOKIE},async()=>{
const base='http://localhost:3001/api/';const request=async(path:string,method='GET',body?:any)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:process.env.HEROES_TEST_COOKIE!},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
const created=await request('Kayohan/transactions','POST',{type:'despesa',area:'trabalho',category:'Teste integração',description:'Teste descartável',value:50,date:'2026-10-05'});assert.equal(created.status,200);const id=created.data.id;
try{assert.equal((await request('Arielle/transactions')).status,403);assert.equal((await request('Arielle/transactions/'+id,'DELETE')).status,403);assert.equal((await request('Arielle/transactions/'+id,'PUT',{...created.data,value:99})).status,403);const updated=await request('Kayohan/transactions/'+id,'PUT',{...created.data,value:60});assert.equal(updated.data.value,60);assert.equal((await request('Kayohan/transactions','POST',{...created.data,value:-1})).status,400);const agent=await request('Kayohan/agent','POST',{message:'Gastei 50 de gasolina hoje'});assert.equal(agent.status,200);assert.equal(agent.data.proposal.action,'create');assert.equal(agent.data.proposal.data.value,50);assert.equal((await request('Kayohan/transactions')).data.filter((e:any)=>e.id===id).length,1);}finally{assert.equal((await request('Kayohan/transactions/'+id,'DELETE')).status,200);}
const f=await request('Kayohan/fixed','POST',{name:'Teste descartável',value:100,day:31,area:'pessoal'});assert.equal(f.status,200);try{assert.equal((await request('Arielle/fixed/'+f.data.id,'DELETE')).status,403);assert.equal((await request('Kayohan/fixed/'+f.data.id,'PUT',{name:'Teste atualizado',value:150,day:15,area:'pessoal'})).data.value,150);}finally{await request('Kayohan/fixed/'+f.data.id,'DELETE');}
});

