import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{scryptSync}from'node:crypto';import{today}from'../src/domain.js';
test('API real: pagamento idempotente, despesa, desfazer e isolamento',async()=>{const original=process.cwd();const keys=['HEROES_NO_LISTEN','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','KAYOHAN_EMAIL','ARIELLE_EMAIL'];const saved=keys.map(k=>process.env[k]);const folder=await mkdtemp(join(tmpdir(),'heroes-pay-test-'));let server:any;try{process.chdir(folder);process.env.HEROES_NO_LISTEN='1';delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;process.env.KAYOHAN_EMAIL='kay@example.test';process.env.ARIELLE_EMAIL='ari@example.test';await mkdir('data');const password='test-password-12345',salt='test-only';await writeFile('data/accounts.json',JSON.stringify([{owner:'Kayohan',email:'kay@example.test',salt,hash:scryptSync(password,salt,64).toString('hex')}]));const{app}=await import('../server/index.js');server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const base=`http://127.0.0.1:${server.address().port}/api/`;let cookie='';async function req(path:string,method='GET',body?:any){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}const login=await req('auth/login','POST',{email:'kay@example.test',password});cookie=login.cookie!;const l=await req('Kayohan/loans','POST',{name:'Teste',value:123.45,installments:3,firstDue:'2026-01-31',area:'pessoal'});assert.equal(l.status,200);const input={kind:'loan',sourceId:l.data.id,number:1,due:'2026-01-31',paidAt:today()};assert.equal((await req('Arielle/pay','POST',input)).status,403);assert.equal((await req('Kayohan/pay','POST',{...input,due:'2026-02-01'})).status,400);const[a,b]=await Promise.all([req('Kayohan/pay','POST',input),req('Kayohan/pay','POST',input)]);assert.equal(a.status,200);assert.equal(a.data.id,b.data.id);const rows=(await req('Kayohan/transactions')).data;assert.equal(rows.length,1);assert.equal(rows[0].value,123.45);assert.equal((await req('Kayohan/transactions/'+rows[0].id,'DELETE')).status,400);assert.equal((await req('Kayohan/pay/'+a.data.id,'DELETE',{})).status,200);assert.equal((await req('Kayohan/transactions')).data.length,0);assert.equal((await req('Kayohan/payments')).data.length,0);const weekday=new Date(today()+'T12:00:00Z').getUTCDay()||7;const f=await req('Kayohan/fixed','POST',{name:'Semanal',value:20,day:weekday,recurrence:'weekly',startDate:today(),area:'trabalho'});assert.equal(f.status,200);const paid=await req('Kayohan/pay','POST',{kind:'fixed',sourceId:f.data.id,number:0,due:today(),paidAt:today()});assert.equal(paid.status,200);assert.equal((await req('Kayohan/transactions')).data[0].area,'trabalho');assert.equal((await req('Kayohan/pay/'+paid.data.id,'DELETE',{})).status,200);
const debt=await req('Kayohan/debts','POST',{name:'Cartão teste',description:'Negociar',value:300});assert.equal(debt.status,200);assert.equal((await req('Arielle/debts')).status,403);assert.equal((await req('Arielle/debts/'+debt.data.id,'PUT',{name:'X',value:1})).status,403);assert.equal((await req('Kayohan/debts/'+debt.data.id,'PUT',{name:'Cartão',description:'Atualizada',value:250})).data.value,250);assert.equal((await req('Kayohan/debts')).data.length,1);assert.equal((await req('Kayohan/transactions')).data.length,0);assert.equal((await req('Kayohan/debts/'+debt.data.id,'DELETE')).status,200);assert.equal((await req('Kayohan/debts')).data.length,0);
const reminderBody={title:'Lembrete de teste descartável',recurrence:'daily',startDate:today(),time:'08:00',weekdays:[],app:true,email:false,hideContent:true,enabled:true};
assert.equal((await req('internal/reminders/run','POST',{})).status,401);
const reminder=await req('Kayohan/reminders','POST',reminderBody);assert.equal(reminder.status,200);assert.ok(reminder.data.nextAt);assert.equal(reminder.data.owner,'Kayohan');
assert.equal((await req('Arielle/reminders/'+reminder.data.id,'PUT',reminderBody)).status,403);
assert.equal((await req('Arielle/reminders/'+reminder.data.id,'DELETE')).status,403);
assert.equal((await req('Kayohan/reminders','POST',{...reminderBody,owner:'Arielle'})).status,400);
const proposal=await req('Kayohan/agent','POST',{message:'Me lembrar de beber água todo dia às 8:00'});assert.equal(proposal.status,200);assert.equal(proposal.data.proposal.target,'reminders');assert.equal((await req('Kayohan/reminders')).data.length,1);
const paused=await req('Kayohan/reminders/'+reminder.data.id,'PUT',{...reminderBody,enabled:false});assert.equal(paused.status,200);assert.equal(paused.data.nextAt,null);assert.notEqual(paused.data.revision,reminder.data.revision);
assert.equal((await req('Kayohan/reminders/'+reminder.data.id,'DELETE')).status,200);assert.equal((await req('Kayohan/reminders')).data.length,0);
}finally{if(server)await new Promise<void>(resolve=>server.close(resolve));process.chdir(original);keys.forEach((key,i)=>{if(saved[i]===undefined)delete process.env[key];else process.env[key]=saved[i];});await rm(folder,{recursive:true,force:true});}});

