import type {Express,Request,Response,NextFunction} from 'express';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {readFile,mkdir,writeFile,rename} from 'node:fs/promises';
import type {Owner} from '../src/domain.js';
type Account={owner:Owner;email:string;salt:string;hash:string};
const sessions=new Map<string,{owner:Owner;expires:number}>();
const attempts=new Map<string,{count:number;until:number}>();
const ttl=12*60*60*1000;
function token(req:Request){return req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('heroes_session='))?.slice('heroes_session='.length);}
function identity(req:Request){const key=token(req);const session=key?sessions.get(key):undefined;if(session&&session.expires>Date.now())return session.owner;if(key)sessions.delete(key);return null;}
function cookie(res:Response,value:string,maxAge:number){res.cookie('heroes_session',value,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production'||!!process.env.VERCEL,path:'/',maxAge});}
export async function installAuth(app:Express,db:SupabaseClient|null){
 const sessionHash=(key:string)=>createHash('sha256').update(key).digest('hex');
 async function resolveIdentity(req:Request){if(!db)return identity(req);const key=token(req);if(!key)return null;const {data,error}=await db.from('auth_sessions').select('owner,expires_at').eq('token_hash',sessionHash(key)).maybeSingle();if(error)throw error;if(!data||new Date(data.expires_at).getTime()<=Date.now())return null;return data.owner as Owner;}
 async function revoke(key:string|undefined){if(!key)return;if(!db){sessions.delete(key);return;}const {error}=await db.from('auth_sessions').delete().eq('token_hash',sessionHash(key));if(error)throw error;}
 type Invite={owner:Owner;email:string;code:string;expires:number};let invites:Invite[]=[];
 if(!db){await mkdir('data',{recursive:true});try{invites=JSON.parse(await readFile('data/invitations.json','utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;}let accounts:Account[]=[];try{accounts=JSON.parse(await readFile('data/accounts.json','utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;}const emails=[['Kayohan',process.env.KAYOHAN_EMAIL],['Arielle',process.env.ARIELLE_EMAIL]] as const;for(const[owner,email]of emails){if(email&&!accounts.some(a=>a.owner===owner)&&!invites.some(a=>a.owner===owner&&a.expires>Date.now()))invites.push({owner,email:email.trim().toLowerCase(),code:randomBytes(32).toString('hex'),expires:Date.now()+7*24*60*60*1000});}await writeFile('data/invitations.json',JSON.stringify(invites,null,2),{mode:0o600});await writeFile('data/primeiro-acesso.md','# Primeiro acesso — links privados\n\nNão publique ou compartilhe o link de uma pessoa com a outra. Expiram em sete dias.\n\n'+invites.filter(i=>!accounts.some(a=>a.owner===i.owner)).map(i=>`${i.owner}: http://localhost:5173/?invite=${i.code}\n\nE-mail: ${i.email}\n`).join('\n'),{mode:0o600});}
 app.use('/api',(req,res,next)=>{if(['POST','PUT','DELETE','PATCH'].includes(req.method)){if(req.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')return res.status(415).json({error:'Formato de solicitação inválido.'});if(req.headers.origin){try{const origin=new URL(req.headers.origin);const allowed=process.env.APP_ORIGIN?.split(',').map(value=>value.trim())||(process.env.NODE_ENV==='production'?[]:['http://localhost:5173','http://127.0.0.1:5173']);if(origin.host!==req.headers.host&&!allowed.includes(origin.origin))return res.status(403).json({error:'Origem não permitida.'});}catch{return res.status(403).json({error:'Origem inválida.'});}}}next();});
 let activationQueue=Promise.resolve();
 app.post('/api/auth/activate',async(req,res)=>{
  if(db)return res.status(400).json({error:'Use a conta criada pelo administrador no Supabase.'});const {email,password,code}=req.body||{};if(typeof email!=='string'||typeof password!=='string'||typeof code!=='string'||password.length<8||password.length>256)return res.status(400).json({error:'Informe seu e-mail e uma senha entre 8 e 256 caracteres.'});
  activationQueue=activationQueue.catch(()=>{}).then(async()=>{const invite=invites.find(i=>i.code===code&&i.email===email.trim().toLowerCase()&&i.expires>Date.now());let accounts:Account[]=[];try{accounts=JSON.parse(await readFile('data/accounts.json','utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;}if(!invite||accounts.some(a=>a.owner===invite.owner||a.email===invite.email)){res.status(400).json({error:'Link inválido, expirado ou já utilizado.'});return;}const salt=randomBytes(16).toString('hex');accounts.push({owner:invite.owner,email:invite.email,salt,hash:scryptSync(password,salt,64).toString('hex')});await writeFile('data/accounts.tmp',JSON.stringify(accounts,null,2),{mode:0o600});await rename('data/accounts.tmp','data/accounts.json');invites=invites.filter(i=>i!==invite);await writeFile('data/invitations.json',JSON.stringify(invites,null,2),{mode:0o600});res.json({ok:true});});try{await activationQueue;}catch{if(!res.headersSent)res.status(500).json({error:'Não foi possível ativar a conta.'});}
 });
 app.post('/api/auth/login',async(req,res)=>{
  const ip=req.ip||'local';const now=Date.now();for(const[key,value]of attempts)if(value.until<now)attempts.delete(key);const previous=attempts.get(ip);if(previous&&previous.count>=10)return res.status(429).json({error:'Muitas tentativas. Aguarde 15 minutos.'});attempts.set(ip,{count:(previous?.count||0)+1,until:previous?.until||now+15*60*1000});
  const {email,password}=req.body||{};if(typeof email!=='string'||typeof password!=='string'||email.length>254||password.length>256)return res.status(401).json({error:'E-mail ou senha incorretos.'});let owner:Owner|null=null;
  try{if(db){const kay=process.env.KAYOHAN_EMAIL?.trim().toLowerCase(),ari=process.env.ARIELLE_EMAIL?.trim().toLowerCase();if(kay&&ari&&kay!==ari){const authClient=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await authClient.auth.signInWithPassword({email,password});if(!error&&data.user){const verified=data.user.email?.toLowerCase();if(verified===kay)owner='Kayohan';else if(verified===ari)owner='Arielle';}}}else{let accounts:Account[]=[];try{accounts=JSON.parse(await readFile('data/accounts.json','utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;}const account=accounts.find(a=>a.email===email.trim().toLowerCase());const salt=account?.salt||'00000000000000000000000000000000';const derived=scryptSync(password,salt,64);const expected=account?Buffer.from(account.hash,'hex'):Buffer.alloc(64);if(account&&expected.length===derived.length&&timingSafeEqual(derived,expected))owner=account.owner;}}catch{ return res.status(503).json({error:'Não foi possível entrar. Confira a configuração do servidor.'});}
  if(!owner)return res.status(401).json({error:'E-mail ou senha incorretos. Se for seu primeiro acesso, configure sua conta no servidor.'});
  attempts.delete(ip);const old=token(req);try{await revoke(old);}catch{return res.status(503).json({error:'Não foi possível renovar a sessão.'});}for(const[key,s]of sessions)if(s.expires<now)sessions.delete(key);const key=randomBytes(32).toString('hex');if(db){const {error}=await db.from('auth_sessions').insert({token_hash:sessionHash(key),owner,expires_at:new Date(now+ttl).toISOString()});if(error)return res.status(503).json({error:'Não foi possível iniciar a sessão. Execute a migration 004_sessions.'});}else sessions.set(key,{owner,expires:now+ttl});cookie(res,key,ttl);res.json({owner});
 });
 app.get('/api/auth/me',async(req,res,next)=>{res.setHeader('Cache-Control','no-store');try{const owner=await resolveIdentity(req);if(!owner)return res.status(401).json({error:'Faça login para continuar.'});res.json({owner});}catch(e){next(e);}});
 app.post('/api/auth/logout',async(req,res,next)=>{try{await revoke(token(req));cookie(res,'',0);res.json({ok:true});}catch(e){next(e);}});
 app.use('/api',async(req:Request,res:Response,next:NextFunction)=>{res.setHeader('Cache-Control','no-store');try{const owner=await resolveIdentity(req);if(!owner)return res.status(401).json({error:'Sua sessão terminou. Entre novamente.'});res.locals.owner=owner;next();}catch(e){next(e);}});
 // Nenhum parâmetro, corpo ou ferramenta pode trocar a identidade da sessão.
 app.param('owner',(req,res,next,value)=>{if(value!==res.locals.owner)return res.status(403).json({error:'Você não tem acesso a este perfil.'});next();});
}





