import {reminderSchema,nextOccurrence,type ScheduledReminder} from '../src/reminders.js';
import {emailReady} from './reminder-mail.js';
import {runReminders} from './reminder-worker.js';
import {timingSafeEqual} from 'node:crypto';
import {quickAgent} from './agent-local.js';
import {debtSchema,type Debt} from '../src/debts.js';
import 'dotenv/config';
import express from 'express';
import {installAuth} from './auth.js';
import {createClient} from '@supabase/supabase-js';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {paymentRequest} from './payments.js';
import {loanSchema,loanSchedule,fixedSchedule,type Loan,type Payment} from '../src/commitments.js';
import {entrySchema,fixedSchema,ownerSchema,select,summary,today,money,type Entry,type Fixed,type Owner} from '../src/domain.js';
const apiKey=process.env.OPENROUTER_API_KEY||process.env.OPENAI_API_KEY;
const aiEndpoint=process.env.OPENROUTER_API_KEY?'https://openrouter.ai/api/v1/chat/completions':'https://api.openai.com/v1/chat/completions';
const aiModel=process.env.OPENROUTER_API_KEY?(process.env.OPENROUTER_MODEL||'nvidia/nemotron-3.5-lightning:free'):(process.env.OPENAI_MODEL||'gpt-4.1-mini');
const app=express();app.use(express.json({limit:'32kb'}));
const db=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY):null;
app.post('/api/internal/reminders/run',async(req,res)=>{
 const expected=process.env.REMINDER_CRON_SECRET||'',given=req.get('Authorization')?.replace(/^Bearer /,'')||'';
 if(!expected||Buffer.byteLength(given)!==Buffer.byteLength(expected)||!timingSafeEqual(Buffer.from(given),Buffer.from(expected)))return res.status(401).json({error:'Não autorizado.'});
 if(!db)return res.status(503).json({error:'Agendamento requer Supabase.'});
 try{res.json(await runReminders(db));}catch{res.status(503).json({error:'Não foi possível processar os lembretes.'});}
});
await installAuth(app,db);
type State={transactions:Entry[];fixed:Fixed[];loans:Loan[];payments:Payment[];debts:Debt[];reminders:ScheduledReminder[]};let state:State={transactions:[],fixed:[],loans:[],payments:[],debts:[],reminders:[]};
if(!db){await mkdir('data',{recursive:true});try{state=JSON.parse(await readFile('data/finance.json','utf8'));}catch(e:any){if(e.code!=='ENOENT')throw e;}}
state.reminders??=[];state.debts??=[];state.loans??=[];state.payments??=[];
let queue=Promise.resolve();async function save(){const snapshot=JSON.stringify(state,null,2);queue=queue.then(async()=>{await writeFile('data/finance.tmp',snapshot);await rename('data/finance.tmp','data/finance.json');});await queue;}
if(!db){let changed=false;for(const f of state.fixed){if(!f.recurrence){f.recurrence='monthly';changed=true;}if(!f.startDate){f.startDate=today();changed=true;}}if(changed)await save();}
async function list(table:'transactions'|'fixed'|'loans'|'payments'|'debts'|'reminders',owner:Owner):Promise<any[]>{if(!db)return state[table].filter(e=>e.owner===owner);const {data,error}=await db.from(table).select('*').eq('owner',owner);if(error)throw error;return data;}
async function mutate(table:'transactions'|'fixed'|'loans'|'payments'|'debts'|'reminders',owner:Owner,action:string,input:any,id?:string){if(table==='payments')throw new Error('Use o fluxo de pagamento.');if(table==='transactions'&&action!=='create'&&(await list('payments',owner)).some(p=>p.transactionId===id))throw new Error('Desfaça o pagamento na conta ou empréstimo antes de alterar este lançamento.');if(table==='loans'&&action==='update'&&(await list('payments',owner)).some(p=>p.kind==='loan'&&p.sourceId===id))throw new Error('Um empréstimo com pagamentos não pode ter seu plano alterado.');const parsed=action==='delete'?null:(table==='transactions'?entrySchema:table==='loans'?loanSchema:table==='debts'?debtSchema:table==='reminders'?reminderSchema:fixedSchema).parse(input);if(table==='reminders'&&parsed){
 if(action==='create'&&(await list('reminders',owner)).length>=50)throw new Error('Limite de 50 lembretes por perfil.');
 const input=parsed as any,nextAt=input.enabled?nextOccurrence(input):null;
 if(input.enabled&&!nextAt)throw new Error('Escolha uma data e horário futuros para este lembrete.');
 Object.assign(parsed,{nextAt,revision:randomUUID()});
 }if(db){let q:any;if(action==='create')q=db.from(table).insert({...parsed,owner,id:randomUUID()}).select();else if(action==='update')q=db.from(table).update(parsed!).eq('owner',owner).eq('id',id).select();else q=db.from(table).delete().eq('owner',owner).eq('id',id).select();const {data,error}=await q;if(error)throw error;if(!data?.length)throw new Error('Registro não encontrado neste perfil');return data[0];}const items=state[table] as any[];if(action==='create'){const row={...parsed,owner,id:randomUUID()};items.push(row);await save();return row;}const index=items.findIndex(e=>e.owner===owner&&e.id===id);if(index<0)throw new Error('Registro não encontrado neste perfil');const old=items[index];if(action==='delete')items.splice(index,1);else items[index]={...parsed,id,owner};await save();return action==='delete'?old:items[index];}
let paymentQueue=Promise.resolve();
app.post('/api/:owner/pay',async(req,res,next)=>{try{const owner=ownerSchema.parse(req.params.owner);const input=paymentRequest.parse(req.body);if(input.paidAt>today())throw new Error('A data do pagamento não pode estar no futuro.');if(db){const {data,error}=await db.rpc('pay_commitment',{p_owner:owner,p_kind:input.kind,p_source:input.sourceId,p_number:input.number,p_due:input.due,p_paid:input.paidAt});if(error)throw new Error(error.message);return res.json(data);}let result:any;paymentQueue=paymentQueue.catch(()=>{}).then(async()=>{const source=input.kind==='loan'?state.loans.find(l=>l.owner===owner&&l.id===input.sourceId):state.fixed.find(f=>f.owner===owner&&f.id===input.sourceId);if(!source)throw new Error('Compromisso não encontrado neste perfil.');const schedule=input.kind==='loan'?loanSchedule(source as Loan,state.payments):fixedSchedule(source as Fixed,state.payments,input.due,input.due);const occurrence=schedule.find(d=>d.due===input.due&&d.number===input.number);if(!occurrence)throw new Error('Vencimento ou parcela inválida.');if(occurrence.payment){result=occurrence.payment;return;}const entry:Entry={id:randomUUID(),owner,type:'despesa',area:source.area,category:input.kind==='loan'?'Empréstimos':'Contas fixas',description:source.name+(input.kind==='loan'?` · parcela ${input.number}/${(source as Loan).installments}`:` · vencimento ${input.due}`),value:source.value,date:input.paidAt};const payment:Payment={...input,id:randomUUID(),owner,transactionId:entry.id,value:entry.value};state.transactions.push(entry);state.payments.push(payment);try{await save();}catch(e){state.transactions=state.transactions.filter(t=>t.id!==entry.id);state.payments=state.payments.filter(p=>p.id!==payment.id);throw e;}result=payment;});await paymentQueue;res.json(result);}catch(e){next(e);}});
app.delete('/api/:owner/pay/:id',async(req,res,next)=>{try{const owner=ownerSchema.parse(req.params.owner);const id=z.uuid().parse(req.params.id);if(db){const {data,error}=await db.rpc('undo_commitment_payment',{p_owner:owner,p_id:id});if(error)throw new Error(error.message);return res.json(data);}paymentQueue=paymentQueue.catch(()=>{}).then(async()=>{const payment=state.payments.find(p=>p.owner===owner&&p.id===id);if(!payment)throw new Error('Pagamento não encontrado neste perfil.');const oldPayments=state.payments,oldEntries=state.transactions;state.payments=state.payments.filter(p=>p.id!==id);state.transactions=state.transactions.filter(t=>t.id!==payment.transactionId);try{await save();}catch(e){state.payments=oldPayments;state.transactions=oldEntries;throw e;}});await paymentQueue;res.json({ok:true});}catch(e){next(e);}});
app.get('/api/health',(_,res)=>res.json({mode:db?'supabase':'local',agent:apiKey?'llm':'local',provider:process.env.OPENROUTER_API_KEY?'openrouter':'openai',model:apiKey?aiModel:null,reminderEmail:emailReady(),reminderTimezone:'America/Sao_Paulo'}));
app.get('/api/:owner/:table',async(req,res,next)=>{if(req.params.table==='agent')return next();try{const owner=ownerSchema.parse(req.params.owner);const table=z.enum(['transactions','fixed','loans','payments','debts','reminders']).parse(req.params.table);res.json(await list(table,owner));}catch(e){next(e);}});
for(const method of ['post','put','delete'] as const)app[method]('/api/:owner/:table{/:id}',async(req,res,next)=>{if(req.params.table==='agent')return next();try{const owner=ownerSchema.parse(req.params.owner);const table=z.enum(['transactions','fixed','loans','payments','debts','reminders']).parse(req.params.table);if(method!=='post')z.uuid().parse(req.params.id);res.json(await mutate(table,owner,method==='post'?'create':method==='put'?'update':'delete',req.body,req.params.id));}catch(e){next(e);}});
const reminderParameters={type:'object',properties:{title:{type:'string'},recurrence:{type:'string',enum:['once','daily','weekly','monthly']},startDate:{type:'string',description:'YYYY-MM-DD'},time:{type:'string',description:'HH:mm em Brasília'},weekdays:{type:'array',items:{type:'integer',minimum:1,maximum:7}},app:{type:'boolean'},email:{type:'boolean'},hideContent:{type:'boolean'},enabled:{type:'boolean'}},required:['title','recurrence','startDate','time','weekdays','app','email','hideContent','enabled'],additionalProperties:false};
const toolDefinitions=[{name:'getReminders',description:'Consulta os lembretes do perfil ativo',parameters:{type:'object',properties:{},additionalProperties:false}},...['createReminder','updateReminder','deleteReminder'].map(name=>({name,description:'Prepara lembrete para confirmação, sem enviar ou salvar ainda. Não inclua destinatário ou owner. IDs devem vir de getReminders.',parameters:name==='deleteReminder'?{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false}:name==='updateReminder'?{...reminderParameters,properties:{...reminderParameters.properties,id:{type:'string'}},required:[...reminderParameters.required,'id']}:reminderParameters})),{name:'getFinancialSummary',description:'Resumo calculado pelo código',parameters:{type:'object',properties:{period:{type:'string',enum:['week','month']}},required:['period'],additionalProperties:false}},{name:'getTransactions',description:'Consulta por período e categoria',parameters:{type:'object',properties:{period:{type:'string',enum:['week','month']},category:{type:'string'}},required:['period'],additionalProperties:false}},...['createTransaction','updateTransaction','deleteTransaction'].map(name=>({name,description:'Prepara uma alteração para confirmação do usuário. Use IDs reais de getTransactions.',parameters:name==='deleteTransaction'?{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false}:{type:'object',properties:{...(name==='updateTransaction'?{id:{type:'string'}}:{}),type:{type:'string',enum:['receita','despesa']},area:{type:'string',enum:['pessoal','trabalho']},category:{type:'string'},description:{type:'string'},value:{type:'number'},date:{type:'string'}},required:[...(name==='updateTransaction'?['id']:[]),'type','area','category','description','value','date'],additionalProperties:false}}))];
async function runTool(owner:Owner,name:string,args:any){
 if(name==='getReminders')return {reminders:await list('reminders',owner)};
 if(['createReminder','updateReminder','deleteReminder'].includes(name)){
 const action=name==='createReminder'?'create':name==='updateReminder'?'update':'delete';
 const {id,...input}=args;
 if(action!=='create'){z.uuid().parse(id);if(!(await list('reminders',owner)).some(r=>r.id===id))throw new Error('Lembrete não encontrado neste perfil.');}
 const data=action==='delete'?null:reminderSchema.parse(input);
 if(data?.enabled&&!nextOccurrence(data))throw new Error('Escolha um horário futuro.');
 return {proposal:{target:'reminders',action,id,data}};
 }
if(name==='getFinancialSummary'||name==='getTransactions'){const period=z.enum(['week','month']).parse(args.period);const rows=select(await list('transactions',owner),owner,period,args.category);return name==='getFinancialSummary'?summary(rows):{transactions:rows,expenseTotal:rows.filter(e=>e.type==='despesa').reduce((s,e)=>s+Math.round(e.value*100),0)/100};}if(!['createTransaction','updateTransaction','deleteTransaction'].includes(name))throw new Error('Ferramenta inválida');const action=name==='createTransaction'?'create':name==='updateTransaction'?'update':'delete';if(action!=='create'){z.uuid().parse(args.id);if(!(await list('transactions',owner)).some(e=>e.id===args.id))throw new Error('Registro não encontrado neste perfil');}return {proposal:{action,id:args.id,data:action==='delete'?null:entrySchema.parse(args)}};}
app.post('/api/:owner/agent',async(req,res,next)=>{try{const owner=ownerSchema.parse(req.params.owner);const message=z.string().trim().min(1).max(1000).parse(req.body.message);const quick=await quickAgent(owner,message,runTool);if(quick)return res.json(quick);if(!apiKey)return res.json({text:'Modo local: use os atalhos de resumo, gasolina ou despesa. Configure um provedor para outras perguntas.'});
const messages:any[]=[{role:'system',content:`Você é Heroes Agent. Perfil ativo: ${owner}. Hoje: ${today()}. Use ferramentas para todos os valores financeiros; nunca calcule números. Não invente registros ou IDs. Receitas/custos de Uber e gasolina são trabalho. Pergunte se faltar informação. Você também cria e consulta lembretes. Interprete repetição e horário, em Brasília. Para frase sem canal, use app=true,email=false,hideContent=true. Não invente horário se não informado. startDate é hoje se não indicado. weekdays: 1=segunda até 7=domingo. Escritas são propostas sujeitas a confirmação. Responda brevemente em português.`},{role:'user',content:message}];let proposal:any;const deadline=Date.now()+40000;for(let step=0;step<5;step++){const response=await fetch(aiEndpoint,{signal:AbortSignal.timeout(Math.max(1,Math.min(12000,deadline-Date.now()))),method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:aiModel,messages,tools:toolDefinitions.map(f=>({type:'function',function:f})),parallel_tool_calls:false,max_tokens:1024})});if(!response.ok)throw new Error(response.status===429?'O modelo gratuito atingiu o limite de uso. Tente novamente mais tarde.':response.status===401?'A chave do serviço de IA não foi aceita. Confira a configuração.':'O serviço de IA não respondeu (HTTP '+response.status+'). Tente novamente.');const result:any=await response.json();const answer=result.choices[0].message;messages.push(answer);if(!answer.tool_calls?.length)return res.json({text:answer.content||'Confira os dados abaixo.',proposal});for(const call of answer.tool_calls){const out:any=await runTool(owner,call.function.name,JSON.parse(call.function.arguments));if(out.proposal){proposal=out.proposal;return res.json({text:'Confira a alteração antes de confirmar.',proposal});}messages.push({role:'tool',tool_call_id:call.id,content:JSON.stringify(out)});}}throw new Error('Limite de consultas atingido. Faça uma pergunta mais específica.');}catch(e){if(e instanceof Error&&e.name==='TimeoutError')return res.status(504).json({error:'A IA demorou para responder. Tente novamente ou use os atalhos de consulta.'});next(e);}});
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err.message);res.status(400).json({error:err instanceof z.ZodError?'Confira os campos informados.':err.message||'Não foi possível concluir.'});});
export {app};
if(!process.env.VERCEL&&process.env.HEROES_NO_LISTEN!=='1')app.listen(Number(process.env.PORT)||3001,'127.0.0.1',()=>console.log(`Heroes API • ${db?'Supabase':'local'} • localhost:${process.env.PORT||3001}`));











