import {heroesConfirm} from './HeroesConfirm';
import{useEffect,useState,type FormEvent}from'react';
import{money,type Owner}from'./domain';
import{debtTotal,type Debt}from'./debts';
export function DebtView({owner}:{owner:Owner}){const[debts,setDebts]=useState<Debt[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState<{id?:string;name:string;description:string;value:string}|null>(null);
 async function request(path='',method='GET',body?:unknown){const r=await fetch(`/api/${owner}/debts${path}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(r.status===401)window.dispatchEvent(new Event('heroes-session-ended'));if(!r.ok)throw new Error(data.error||'Não foi possível concluir.');return data;}
 async function refresh(){setDebts(await request());}
 useEffect(()=>{let active=true;request().then(data=>{if(active)setDebts(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[owner]);
 async function save(e:FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setError('');try{await request(draft.id?'/'+draft.id:'',draft.id?'PUT':'POST',{name:draft.name,description:draft.description,value:Number(draft.value)});await refresh();setDraft(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function remove(debt:Debt){if(!await heroesConfirm(`Excluir a dívida “${debt.name}” da lista de negociação?`))return;setBusy(true);setError('');try{await request('/'+debt.id,'DELETE');await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="debts"><div className="panel-title"><div><h3>Contas a negociar</h3><p>Organize as dívidas que ainda precisam de um acordo.</p></div><button className="primary" disabled={busy} onClick={()=>{setError('');setDraft({name:'',description:'',value:''});}}>+ Nova dívida</button></div>{error&&!draft&&<p role="alert" className="error">{error}</p>}{loading?<div className="empty">Carregando suas dívidas…</div>:<><div className="debt-list">{debts.map(d=><article className="panel debt-row" key={d.id}><div className="debt-details"><span className="eyebrow">A NEGOCIAR</span><h3>{d.name}</h3>{d.description&&<p>{d.description}</p>}</div><div className="debt-amount"><strong>{money(d.value)}</strong><div><button disabled={busy} onClick={()=>{setError('');setDraft({...d,value:String(d.value)});}}>Editar</button><button disabled={busy} className="red" onClick={()=>remove(d)}>Excluir</button></div></div></article>)}</div>{!debts.length&&<div className="empty">Nenhuma dívida a negociar cadastrada.</div>}<div className="panel debt-total"><div><span className="eyebrow">TOTAL DAS DÍVIDAS A NEGOCIAR</span><p>{debts.length} {debts.length===1?'dívida cadastrada':'dívidas cadastradas'} · {owner}</p></div><h2>{money(debtTotal(debts,owner))}</h2></div><p className="note">Este total considera apenas as dívidas desta aba. O cadastro não altera o saldo financeiro. Registre pagamentos no Extrato ou cadastre o acordo em Empréstimos; atualize ou exclua a dívida negociada.</p></>}{draft&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label={draft.id?'Editar dívida':'Nova dívida'}><div className="panel-title"><h3>{draft.id?'Editar dívida':'Nova dívida'}</h3><button disabled={busy} aria-label="Fechar dívida" onClick={()=>setDraft(null)}>×</button></div><p>Perfil: {owner}</p><form onSubmit={save}><label>Conta / credor<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ex.: Cartão, banco ou loja"/></label><label>Valor atual da dívida (R$)<input required type="number" min="0.01" max="10000000" step="0.01" value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label><label>Observações<textarea maxLength={500} rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Detalhes para a negociação (opcional)"/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar dívida'}</button></div></form></section></div>}</section>;
}
