import {useState,type FormEvent} from 'react';
import type {Owner} from './domain';
export function Login({onLogin}:{onLogin:(owner:Owner)=>void}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const[showPassword,setShowPassword]=useState(false);const[invite,setInvite]=useState(()=>new URLSearchParams(window.location.search).get('invite'));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(invite){const activation=await fetch('/api/auth/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,code:invite})});const result=await activation.json();if(!activation.ok)throw new Error(result.error);window.history.replaceState(null,'',window.location.pathname);setInvite(null);}const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error);setPassword('');onLogin(data.owner);}catch(e:any){setError(e.message||'Não foi possível entrar.');}finally{setBusy(false);}}
 return <main className="login-screen"><section className="login-card panel"><div className="login-brand"><img src="/logo-heroes.svg" alt="Heroes"/><span>HEROES <small>FINANCE</small></span></div><div className="eyebrow">{invite?'PRIMEIRO ACESSO':'SEU WORKSPACE PESSOAL'}</div><h1>Seu dinheiro, só seu.</h1><p>{invite?'Confirme seu e-mail e crie sua senha para ativar sua conta.':'Entre para acessar seus lançamentos e seu histórico.'}</p><form onSubmit={submit}><label>E-mail<input required type="email" autoComplete="username" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{invite?'Crie sua senha (mínimo 8 caracteres)':'Senha'}<span className="password-field"><input id="login-password" required type={showPassword?"text":"password"} minLength={invite?8:undefined} autoComplete={invite?'new-password':'current-password'} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></span></label><div className="password-visibility"><button type="button" className="password-toggle" aria-controls="login-password" aria-pressed={showPassword} onClick={()=>setShowPassword(v=>!v)}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>{showPassword&&<path d="m3 3 18 18"/>}</svg>{showPassword?"Ocultar senha":"Mostrar senha"}</button></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Entrando…':invite?'Criar senha e entrar':'Entrar'}</button></form><p className="login-note">O perfil é definido pela sua conta. Cada pessoa acessa apenas seus próprios registros.</p></section></main>;
}



