import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Owner} from './domain';
const steps=[{target:'.metrics',title:'Seu dinheiro em perspectiva',text:'Veja quanto entrou, os custos do trabalho, os gastos pessoais e o que realmente sobrou.'},{target:'.heading>.primary',title:'Registre seu primeiro movimento',text:'Adicione uma receita ou despesa com valor, categoria e data. Os indicadores se atualizam automaticamente.'},{target:'.top-tabs',title:'Organize seus compromissos',text:'Em Contas Fixas, acompanhe contas mensais e semanais, empréstimos e dívidas a negociar. Use o Extrato para conferir seu histórico.'},{target:'#heroes-agent',title:'Converse com seus números',text:'Pergunte quanto sobrou ou diga “Gastei 50 de gasolina hoje”. Confira e confirme a proposta antes de salvar.'},{target:'.heroes-quick-toggle',title:'Heroes sempre à mão',text:'Use o botão flutuante para registrar gastos, receitas, abrir o agente e consultar vencimentos.'}];
export function Onboarding({owner,ready,onStart}:{owner:Owner;ready:boolean;onStart:()=>void}){const key=`heroes-tour-v1-${owner}`;const[active,setActive]=useState(false),[index,setIndex]=useState(0),[rect,setRect]=useState<DOMRect|null>(null);const panel=useRef<HTMLElement>(null),previous=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(!ready)return;try{if(!localStorage.getItem(key)){localStorage.setItem(key,'seen');previous.current=document.activeElement as HTMLElement;onStart();setActive(true);}}catch{}},[ready,key]);
 useEffect(()=>{const replay=()=>{previous.current=document.activeElement as HTMLElement;onStart();setIndex(0);setActive(true);};window.addEventListener('heroes-replay-tour',replay);return()=>window.removeEventListener('heroes-replay-tour',replay);},[onStart]);
 function finish(){try{localStorage.setItem(key,'done');}catch{}setActive(false);previous.current?.focus({preventScroll:true});}
 useLayoutEffect(()=>{if(!active)return;let frame=0;const measure=()=>{const element=document.querySelector<HTMLElement>(steps[index].target);setRect(element?.getBoundingClientRect()||null);};frame=requestAnimationFrame(()=>{document.querySelector(steps[index].target)?.scrollIntoView({block:'center',behavior:'instant'});measure();panel.current?.focus({preventScroll:true});});window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true);};},[active,index]);
 if(!active)return null;
 const width=Math.min(350,window.innerWidth-32),height=300;const bottom=rect?rect.bottom+18:window.innerHeight/2-height/2;const top=rect?(bottom+height<window.innerHeight-16?bottom:Math.max(16,rect.top-height-18)):Math.max(16,bottom);const left=rect?Math.max(16,Math.min(rect.left,window.innerWidth-width-16)):(window.innerWidth-width)/2;
 return createPortal(<div className="tour-layer" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();finish();}if(e.key==='Tab'){const buttons=Array.from(panel.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')||[]);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><div className="tour-shade"/>{rect&&<div className="tour-highlight" style={{top:rect.top-6,left:rect.left-6,width:rect.width+12,height:rect.height+12}}/>}<section ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-description" className="tour-card" style={{top,left,width}}><div className="tour-meta"><span>PRIMEIROS PASSOS / {index+1} DE {steps.length}</span><button onClick={finish}>Pular</button></div><h3 id="tour-title">{steps[index].title}</h3><p id="tour-description">{steps[index].text}</p><div className="tour-progress">{steps.map((_,i)=><span key={i} className={i===index?'active':''}/>)}</div><div className="tour-actions"><button disabled={index===0} onClick={()=>setIndex(index-1)}>Voltar</button><button className="primary" onClick={()=>index===steps.length-1?finish():setIndex(index+1)}>{index===steps.length-1?'Começar a usar':'Próximo →'}</button></div></section></div>,document.body);
}


