import {useEffect,useRef,useState} from 'react';
export type QuickAction='expense'|'income'|'agent'|'reminders';
export function QuickActions({onAction,disabled}:{onAction:(action:QuickAction)=>void;disabled:boolean}){
 const[open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null),toggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[open]);
 const items:{action:QuickAction;icon:string;title:string;detail:string}[]=[{action:'expense',icon:'expense',title:'Novo gasto',detail:'Registrar uma despesa'},{action:'income',icon:'income',title:'Nova receita',detail:'Registrar uma entrada'},{action:'agent',icon:'agent',title:'Heroes Agent',detail:'Conversar com seus números'},{action:'reminders',icon:'reminders',title:'Próximos vencimentos',detail:'Consultar lembretes de pagamento'}];
 return <div className="heroes-quick" ref={root}>{open&&<section id="heroes-quick-menu" className="heroes-quick-menu" aria-label="Atalhos rápidos Heroes"><div className="quick-heading"><span>HEROES / ATALHOS</span><button aria-label="Fechar atalhos" onClick={()=>{setOpen(false);toggle.current?.focus();}}>×</button></div>{items.map(item=><button key={item.action} disabled={disabled} onClick={()=>{setOpen(false);onAction(item.action);}}><span className={'quick-icon '+(item.action==='expense'?'red':item.action==='income'?'green':'amber')}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{item.action==="expense"?<><path d="M7 7h10v10M17 7 7 17"/></>:item.action==="income"?<><path d="M17 17H7V7M7 17 17 7"/></>:item.action==="agent"?<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>:<><rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-8 4h4"/></>}</svg></span><span><strong>{item.title}</strong><small>{item.detail}</small></span><span className="quick-arrow">↗</span></button>)}</section>}<button ref={toggle} className={'heroes-quick-toggle '+(open?'open':'')} aria-label={open?'Fechar atalhos Heroes':'Abrir atalhos Heroes'} aria-expanded={open} aria-controls={open?'heroes-quick-menu':undefined} onClick={()=>setOpen(!open)}><img src="/logo-heroes.svg" alt=""/><span className="quick-toggle-mark">{open?'×':'+'}</span></button></div>;
}

