import {useEffect,useRef,useState} from 'react';
export type QuickAction='expense'|'income'|'agent'|'reminders';
export function QuickActions({onAction,disabled}:{onAction:(action:QuickAction)=>void;disabled:boolean}){
 const [position,setPosition]=useState<{x:number;y:number}|null>(null),[dragging,setDragging]=useState(false);
 const drag=useRef<{id:number;x:number;y:number;left:number;top:number;moved:boolean}|null>(null),suppressClick=useRef(false);
 const bounds=(x:number,y:number)=>({x:Math.max(14,Math.min(window.innerWidth-68,x)),y:Math.max(90,Math.min(window.innerHeight-174,y))});
 useEffect(()=>{
  const restore=()=>{if(window.innerWidth>700){setPosition(null);return;}let side='right',ratio=.8;try{const saved=JSON.parse(localStorage.getItem('heroes-shortcut-position-v1')||'null');if(saved&&(saved.side==='left'||saved.side==='right')&&Number.isFinite(saved.ratio)){side=saved.side;ratio=Math.max(0,Math.min(1,saved.ratio));}}catch{}setPosition(bounds(side==='left'?14:window.innerWidth-68,ratio*window.innerHeight));};
  const keyboard=()=>{const viewport=window.visualViewport;const field=document.activeElement;const editing=field instanceof HTMLTextAreaElement||(field instanceof HTMLInputElement&&!['checkbox','radio','button','submit','file'].includes(field.type));document.documentElement.dataset.mobileKeyboard=(editing||(viewport&&window.innerHeight-viewport.height>150))?'true':'false';};
  document.addEventListener('focusin',keyboard);document.addEventListener('focusout',keyboard);restore();window.addEventListener('resize',restore);window.visualViewport?.addEventListener('resize',keyboard);keyboard();
  return()=>{document.removeEventListener('focusin',keyboard);document.removeEventListener('focusout',keyboard);window.removeEventListener('resize',restore);window.visualViewport?.removeEventListener('resize',keyboard);delete document.documentElement.dataset.mobileKeyboard;};
 },[]);
 const finishDrag=()=>{const current=drag.current;if(!current)return;suppressClick.current=current.moved;drag.current=null;setDragging(false);if(current.moved)setPosition(p=>{if(!p)return p;const next=bounds(p.x+27<window.innerWidth/2?14:window.innerWidth-68,p.y);try{localStorage.setItem('heroes-shortcut-position-v1',JSON.stringify({side:next.x<window.innerWidth/2?'left':'right',ratio:next.y/window.innerHeight}));}catch{}return next;});};
 const[open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null),toggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[open]);
 const items:{action:QuickAction;icon:string;title:string;detail:string}[]=[{action:'expense',icon:'expense',title:'Novo gasto',detail:'Registrar uma despesa'},{action:'income',icon:'income',title:'Nova receita',detail:'Registrar uma entrada'},{action:'agent',icon:'agent',title:'Heroes Agent',detail:'Conversar com seus números'},{action:'reminders',icon:'reminders',title:'Próximos vencimentos',detail:'Consultar lembretes de pagamento'}];
 return <div className={"heroes-quick"+(dragging?" dragging":"")+(position&&position.x<100?" dock-left":"")+(position&&position.y<window.innerHeight/2?" menu-below":"")} style={position?{left:position.x,top:position.y,right:"auto",bottom:"auto"}:undefined} ref={root}>{open&&<section id="heroes-quick-menu" className="heroes-quick-menu" aria-label="Atalhos rápidos Heroes"><div className="quick-heading"><span>HEROES / ATALHOS</span><button aria-label="Fechar atalhos" onClick={()=>{setOpen(false);toggle.current?.focus();}}>×</button></div>{items.map(item=><button key={item.action} disabled={disabled} onClick={()=>{setOpen(false);onAction(item.action);}}><span className={'quick-icon '+(item.action==='expense'?'red':item.action==='income'?'green':'amber')}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{item.action==="expense"?<><path d="M7 7h10v10M17 7 7 17"/></>:item.action==="income"?<><path d="M17 17H7V7M7 17 17 7"/></>:item.action==="agent"?<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>:<><rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-8 4h4"/></>}</svg></span><span><strong>{item.title}</strong><small>{item.detail}</small></span><span className="quick-arrow">↗</span></button>)}</section>}<button ref={toggle} className={'heroes-quick-toggle '+(open?'open':'')} aria-label={open?'Fechar atalhos Heroes':'Abrir atalhos Heroes'} aria-expanded={open} aria-controls={open?'heroes-quick-menu':undefined} onPointerDown={e=>{if(!position||e.button!==0)return;suppressClick.current=false;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,left:position.x,top:position.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const current=drag.current;if(!current||e.pointerId!==current.id)return;const dx=e.clientX-current.x,dy=e.clientY-current.y;if(!current.moved&&Math.hypot(dx,dy)<7)return;current.moved=true;setDragging(true);setOpen(false);setPosition(bounds(current.left+dx,current.top+dy));}} onPointerUp={finishDrag} onPointerCancel={finishDrag} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return;}setOpen(!open);}}><img src="/logo-heroes.svg" alt=""/><span className="quick-toggle-mark">{open?'×':'+'}</span></button></div>;
}

