import {formatTimeInput} from './time-input';
import {useState} from 'react';
import {DateField} from './Fields';
import {today,type Owner} from './domain';
import {reminderInstant,type ScheduledReminder} from './reminders';
export function ReminderSnooze({title,onCancel,onSave}:{title:string;onCancel:()=>void;onSave:(until:string)=>Promise<void>}){
 const [date,setDate]=useState(today()),[time,setTime]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async(until:string)=>{setBusy(true);setError('');try{await onSave(until);onCancel();}catch(e){setError(e instanceof Error?e.message:'Não foi possível adiar.');}finally{setBusy(false);}};
 return <div className="overlay"><section className="modal entry-modal" role="dialog" aria-modal="true" aria-label="Adiar lembrete"><div className="panel-title"><h3>Adiar lembrete</h3><button disabled={busy} aria-label="Fechar" onClick={onCancel}>×</button></div><p>{title}</p><div className="snooze-quick">{[[10,'10 minutos'],[60,'1 hora']] .map(([minutes,label])=><button key={minutes} disabled={busy} onClick={()=>void save(new Date(Date.now()+Number(minutes)*60000).toISOString())}>{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();void save(reminderInstant(date,time));}}><label>Outro dia<DateField label="Data para adiar" value={date} onChange={setDate} required/></label><label>Horário de Brasília<input required type="text" inputMode="numeric" pattern="([01][0-9]|2[0-3]):[0-5][0-9]" placeholder="08:00" maxLength={5} value={time} onChange={e=>setTime(formatTimeInput(e.target.value,time))}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" disabled={busy} onClick={onCancel}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Adiar'}</button></div></form></section></div>;
}
export function ReminderHistory({rows,owner,onChange}:{rows:ScheduledReminder[];owner:Owner;onChange:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const items=rows.flatMap(r=>(r.completionHistory||[]).map(h=>({...h,id:r.id,canUndo:!!r.completedThrough&&new Date(h.at).getTime()===new Date(r.completedThrough).getTime()}))).sort((a,b)=>b.completedAt.localeCompare(a.completedAt));
 return <section className="panel reminder-history"><div className="panel-title"><h3>Concluídos</h3><span className="tag">{items.length} confirmações</span></div>{error&&<p className="error" role="alert">{error}</p>}{!items.length?<p>Suas próximas confirmações aparecerão aqui.</p>:items.slice(0,50).map(h=><div className="reminder-row" key={h.id+h.at}><div><strong>{h.title}</strong><small>Feito em {new Date(h.completedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></div>{h.canUndo&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch(`/api/${owner}/reminders/${h.id}/undo`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({at:h.at})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível desfazer.');await onChange();}catch(e){setError(e instanceof Error?e.message:'Não foi possível desfazer.');}finally{setBusy(false);}}}>Desfazer</button>}</div>)}</section>;
}
