import {useEffect,useState} from 'react';
import {settingsSchema,type UserSettings} from './settings';
import {androidMessage} from './AndroidOptions';
import type {Owner} from './domain';
type DeviceState={notifications:boolean;biometry:boolean};
async function photo(file:File){
 const supported=['image/jpeg','image/jpg','image/png','image/webp'].includes(file.type)||(!file.type&&/\.(jpe?g|png|webp)$/i.test(file.name));
 if(!supported||file.size>8*1024*1024)throw new Error('Escolha uma imagem JPEG, PNG ou WebP de até 8 MB.');
 const url=URL.createObjectURL(file),image=new Image();
 try{
  await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Não foi possível ler a foto. Use JPEG, PNG ou WebP.'));image.src=url;});
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(!ctx)throw new Error('Não foi possível preparar a foto.');
  const side=Math.min(image.naturalWidth,image.naturalHeight);if(!side)throw new Error('Foto inválida.');
  for(const [size,quality] of [[192,.8],[160,.7],[128,.6]]){canvas.width=canvas.height=size;ctx.fillStyle='#141a22';ctx.fillRect(0,0,size,size);ctx.drawImage(image,(image.naturalWidth-side)/2,(image.naturalHeight-side)/2,side,side,0,0,size,size);const data=canvas.toDataURL('image/jpeg',quality);if(data.length<=40000)return data;}
  throw new Error('Não foi possível reduzir a foto para salvar.');
 }finally{URL.revokeObjectURL(url);}
}
export function SettingsView({owner,value,email,onSave,onLogout}:{owner:Owner;value:UserSettings;email:string;onSave:(settings:UserSettings)=>Promise<void>;onLogout:()=>void}){
 const [draft,setDraft]=useState(value),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[device,setDevice]=useState<DeviceState|null>(null);
 const native=!!window.HeroesAndroid;
 useEffect(()=>{setDraft(d=>({...d,theme:value.theme}));},[value.theme]);
 useEffect(()=>{const receive=(e:Event)=>{const data=(e as CustomEvent).detail;if(typeof data?.notifications==='boolean'&&typeof data?.biometry==='boolean')setDevice(data);};window.addEventListener('heroes-device-state',receive);const refresh=()=>{if(document.visibilityState==='visible')androidMessage('deviceState');};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);androidMessage('deviceState');return()=>{window.removeEventListener('heroes-device-state',receive);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[]);
 const set=<K extends keyof UserSettings>(key:K,v:UserSettings[K])=>{setDraft(d=>({...d,[key]:v}));setNotice('');};
 return <div className="settings-page"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await onSave(settingsSchema.parse(draft));setNotice('Configurações salvas na sua conta.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="eyebrow">SUA IDENTIDADE</span><h3>Perfil pessoal</h3></div><span className="tag">{owner}</span></div><div className="settings-photo"><span className="account-avatar large">{draft.avatar?<img src={draft.avatar} alt="Sua foto de perfil"/>:draft.displayName.slice(0,1).toUpperCase()}</span><div><label className="photo-upload">Alterar foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{const avatar=await photo(file);await onSave({...value,avatar});set('avatar',avatar);setNotice('Foto salva na sua conta.');}catch(e){setError(e instanceof Error?e.message:'Foto inválida.');}finally{setBusy(false);}}}/></label>{draft.avatar&&<button type="button" className="text-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onSave({...value,avatar:''});set('avatar','');setNotice('Foto removida da sua conta.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover a foto.');}finally{setBusy(false);}}}>Remover foto</button>}<p>Recorte central automático. Sua foto fica privada.</p></div></div><label className="settings-field">Nome de exibição<input required maxLength={40} value={draft.displayName} onChange={e=>set('displayName',e.target.value)}/></label><label className="settings-field">E-mail de acesso<input readOnly value={email} aria-describedby="account-email-note"/></label><p id="account-email-note" className="note">Este e-mail define o acesso ao seu perfil. A troca exige atualização da conta e da vinculação pelo administrador; editar seu nome ou foto não altera seus registros.</p></section>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="eyebrow">DO SEU JEITO</span><h3>Dashboard</h3></div></div><fieldset className="settings-period"><legend>Aparência</legend>{[['dark','Escuro'],['light','Claro']].map(([v,label])=><label key={v}><input type="radio" name="theme" checked={draft.theme===v} onChange={()=>set('theme',v as 'dark'|'light')}/>{label}</label>)}</fieldset><fieldset className="settings-period"><legend>Período ao entrar</legend>{[['week','Semana'],['month','Mês']].map(([v,label])=><label key={v}><input type="radio" name="default-period" checked={draft.defaultPeriod===v} onChange={()=>set('defaultPeriod',v as 'week'|'month')}/>{label}</label>)}</fieldset>{([['hideBalances','Ocultar valores','Proteja os números no Dashboard e nos Lançamentos.'],['showAgent','Heroes Agent','Converse com seus números no dashboard.'],['showFlow','Fluxo do período','Visualize entradas e saídas.'],['showPaymentReminders','Lembretes de pagamento','Mostre contas e parcelas próximas.'],['showPersonalReminders','Seus lembretes','Mostre os próximos avisos da sua rotina.']] as const).map(([key,title,description])=><label className="settings-toggle" key={key}><div><strong>{title}</strong><small>{description}</small></div><input type="checkbox" checked={draft[key]} onChange={e=>set(key,e.target.checked)}/></label>)}<p className="note">Ocultar um card não cancela seus lembretes nem modifica os dados financeiros.</p></section>
 <div className="settings-save">{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="settings-success" role="status">{notice}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></form>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="eyebrow">ESTE APARELHO</span><h3>Notificações e proteção</h3></div><span className="tag">{native?'ANDROID':'NAVEGADOR'}</span></div>{native?<><p>Atualizações do aplicativo chegam por download seguro. O Android pede sua confirmação para instalar.</p><button onClick={()=>androidMessage('checkUpdate')}>Buscar atualização do app</button><p>Notificações: <strong>{device?device.notifications?'permitidas':'desativadas':'consulte nas configurações do Android'}</strong></p><div className="settings-actions"><button onClick={()=>androidMessage('notifications')}>Permitir notificações</button><button onClick={()=>androidMessage('notificationSettings')}>Configurações do Android</button><button onClick={()=>androidMessage('deviceState')}>Atualizar status</button></div><p>Bloqueio do app: <strong>{device?device.biometry?'ativado':'desativado':'status disponível no APK atualizado'}</strong></p><button onClick={()=>androidMessage(device?.biometry?'biometryOff':'biometry')}>{device?.biometry?'Desativar bloqueio':'Ativar biometria / bloqueio'}</button>{!device&&<p className="note">Instale o APK atualizado para consultar status, abrir permissões e escolher foto pelo seletor nativo.</p>}</>:<p>As permissões de notificações e o bloqueio biométrico são gerenciados no aplicativo Android. Esta versão web não envia notificações push. Abra Configurações no app para ajustar o aparelho.</p>}<p className="note">Permissões são controladas pelo sistema. Pausar lembretes é feito na aba Lembretes; permissões deste aparelho não alteram o envio por e-mail.</p></section>
 <section className="panel settings-panel"><div className="panel-title"><h3>Conta e ajuda</h3></div><div className="settings-actions"><button onClick={()=>{window.dispatchEvent(new Event('heroes-replay-tour'));}}>Rever primeiros passos</button><button className="red" onClick={onLogout}>Sair da conta</button></div></section></div>;
}
