import {useEffect,useState} from 'react';
import {settingsSchema,type UserSettings} from './settings';
import {androidMessage} from './AndroidOptions';
import type {Owner} from './domain';
type DeviceState={notifications:boolean;biometry:boolean;version?:string;checkedAt?:number;exactAlarms?:boolean;scheduled?:number};
async function photo(file:File){
 const supported=['image/jpeg','image/jpg','image/png','image/webp'].includes(file.type)||(!file.type&&/\.(jpe?g|png|webp)$/i.test(file.name));
 if(!supported||file.size>8*1024*1024)throw new Error('Escolha uma imagem JPEG, PNG ou WebP de até 8 MB.');
 const url=URL.createObjectURL(file),image=new Image();
 try{
  await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Não foi possível ler a foto. Use JPEG, PNG ou WebP.'));image.src=url;});
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(!ctx)throw new Error('Não foi possível preparar a foto.');
  const side=Math.min(image.naturalWidth,image.naturalHeight);if(!side)throw new Error('Foto inválida.');
  for(const [size,quality] of [[192,.8],[160,.7],[128,.6]]){canvas.width=canvas.height=size;ctx.fillStyle='#141a22';ctx.fillRect(0,0,size,size);ctx.drawImage(image,(image.naturalWidth-side)/2,(image.naturalHeight-side)/2,side,side,0,0,size,size);const data=canvas.toDataURL('image/jpeg',quality);if(data.length<=40000)return data;}
  throw new Error('Não foi possível reduzir a foto para salvar.');
 }finally{URL.revokeObjectURL(url);}
}
export function SettingsView({owner,value,email,onSave,onLogout}:{owner:Owner;value:UserSettings;email:string;onSave:(settings:UserSettings)=>Promise<void>;onLogout:()=>void}){
 const [draft,setDraft]=useState(value),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[device,setDevice]=useState<DeviceState|null>(null),[deviceNotice,setDeviceNotice]=useState(''),[devicePending,setDevicePending]=useState(false);
 const native=!!window.HeroesAndroid;
 useEffect(()=>{setDraft(d=>({...d,theme:value.theme}));},[value.theme]);
 useEffect(()=>{const receive=(e:Event)=>{const data=(e as CustomEvent).detail;if(typeof data?.notifications==='boolean'&&typeof data?.biometry==='boolean'){setDevice(data);setDevicePending(false);setDeviceNotice(data.notifications?'Android confirmou: notificações permitidas.':'Android confirmou: notificações desativadas.');}};window.addEventListener('heroes-device-state',receive);const refresh=()=>{if(document.visibilityState==='visible')androidMessage('deviceState');};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);androidMessage('deviceState');return()=>{window.removeEventListener('heroes-device-state',receive);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[]);
 useEffect(()=>{if(!devicePending)return;const timeout=window.setTimeout(()=>{setDevicePending(false);setDeviceNotice('O Android não respondeu. Instale o APK 1.4.3 ou mais recente e tente novamente.');},5000);return()=>window.clearTimeout(timeout);},[devicePending]);
 const deviceAction=(action:string)=>{setDevicePending(true);setDeviceNotice(action==='notificationSettings'?'Ative as notificações no Android e volte ao Heroes.':'Aguardando confirmação do Android…');androidMessage(action);};
 const set=<K extends keyof UserSettings>(key:K,v:UserSettings[K])=>{setDraft(d=>({...d,[key]:v}));setNotice('');};
 return <div className="settings-page"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await onSave(settingsSchema.parse(draft));setNotice('Configurações salvas na sua conta.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="eyebrow">SUA IDENTIDADE</span><h3>Perfil pessoal</h3></div><span className="tag">{owner}</span></div><div className="settings-photo"><span className="account-avatar large">{draft.avatar?<img src={draft.avatar} alt="Sua foto de perfil"/>:draft.displayName.slice(0,1).toUpperCase()}</span><div><label className="photo-upload">Alterar foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{const avatar=await photo(file);await onSave({...value,avatar});set('avatar',avatar);setNotice('Foto salva na sua conta.');}catch(e){setError(e instanceof Error?e.message:'Foto inválida.');}finally{setBusy(false);}}}/></label>{draft.avatar&&<button type="button" className="text-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onSave({...value,avatar:''});set('avatar','');setNotice('Foto removida da sua conta.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover a foto.');}finally{setBusy(false);}}}>Remover foto</button>}<p>Recorte central automático. Sua foto fica privada.</p></div></div><label className="settings-field">Nome de exibição<input required maxLength={40} value={draft.displayName} onChange={e=>set('displayName',e.target.value)}/></label><label className="settings-field">E-mail de acesso<input readOnly value={email} aria-describedby="account-email-note"/></label><p id="account-email-note" className="note">Este e-mail define o acesso ao seu perfil. A troca exige atualização da conta e da vinculação pelo administrador; editar seu nome ou foto não altera seus registros.</p></section>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="eyebrow">DO SEU JEITO</span><h3>Dashboard</h3></div></div><fieldset className="settings-period"><legend>Aparência</legend>{[['dark','Escuro'],['light','Claro']].map(([v,label])=><label key={v}><input type="radio" name="theme" checked={draft.theme===v} onChange={()=>set('theme',v as 'dark'|'light')}/>{label}</label>)}</fieldset><fieldset className="settings-period"><legend>Período ao entrar</legend>{[['week','Semana'],['month','Mês']].map(([v,label])=><label key={v}><input type="radio" name="default-period" checked={draft.defaultPeriod===v} onChange={()=>set('defaultPeriod',v as 'week'|'month')}/>{label}</label>)}</fieldset>{([['hideBalances','Ocultar valores','Proteja os números no Dashboard e nos Lançamentos.'],['showAgent','Heroes Agent','Converse com seus números no dashboard.'],['showFlow','Fluxo do período','Visualize entradas e saídas.'],['showPaymentReminders','Lembretes de pagamento','Mostre contas e parcelas próximas.'],['showPersonalReminders','Seus lembretes','Mostre os próximos avisos da sua rotina.']] as const).map(([key,title,description])=><label className="settings-toggle" key={key}><div><strong>{title}</strong><small>{description}</small></div><input type="checkbox" checked={draft[key]} onChange={e=>set(key,e.target.checked)}/></label>)}<p className="note">Ocultar um card não cancela seus lembretes nem modifica os dados financeiros.</p></section>
 <div className="settings-save">{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="settings-success" role="status">{notice}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></form>
 <section className="panel settings-panel device-panel"><div className="panel-title"><div><span className="eyebrow">ESTE APARELHO</span><h3>Notificações e proteção</h3></div><span className="tag">{native?'ANDROID':'WEB'}</span></div>{native?<>
 <div className="device-summary"><span className={'device-dot '+(device?.notifications&&device?.exactAlarms?'ready':'')}/><div><strong>{device?device.notifications&&device.exactAlarms?'Pronto para seus lembretes':'Conclua a configuração':'Verificando aparelho'}</strong><small>{device?.scheduled??0} avisos futuros · APK {device?.version||'—'}</small></div><button aria-label="Atualizar status do aparelho" disabled={devicePending} onClick={()=>deviceAction('deviceState')}>↻</button></div>
 <div className="device-grid"><article className="device-setting"><div className="device-setting-title"><h4>Notificações</h4><span className={'device-badge '+(device?.notifications?'ready':'')}>{device?device.notifications?'Permitidas':'Desativadas':'Verificando'}</span></div><p>Receba os títulos dos seus lembretes.</p><button className={device?.notifications?'':'primary'} disabled={devicePending} onClick={()=>deviceAction(device?.notifications?'notificationSettings':'notifications')}>{device?.notifications?'Gerenciar no Android':'Permitir notificações'}</button></article>
 <article className="device-setting"><div className="device-setting-title"><h4>Horários precisos</h4><span className={'device-badge '+(device?.exactAlarms?'ready':'')}>{device?.exactAlarms?'Permitidos':'Configurar'}</span></div><p>{device?.exactAlarms?'Seus avisos usam o horário escolhido.':'Autorize o agendamento no horário escolhido.'}</p>{!device?.exactAlarms&&<button disabled={devicePending} className="primary" onClick={()=>deviceAction('exactAlarms')}>Permitir horários precisos</button>}</article>
 <article className="device-setting"><div className="device-setting-title"><h4>Proteção de acesso</h4><span className={'device-badge '+(device?.biometry?'ready':'')}>{device?.biometry?'Ativada':'Opcional'}</span></div><p>Biometria ou bloqueio do aparelho ao abrir.</p><button disabled={devicePending||!device} onClick={()=>deviceAction(device?.biometry?'biometryOff':'biometry')}>{device?.biometry?'Desativar bloqueio':'Ativar proteção'}</button></article>
 <article className="device-setting"><div className="device-setting-title"><h4>Atualizações</h4><span className="device-badge">APK {device?.version||'—'}</span></div><p>Busque a versão mais recente do Heroes.</p><button onClick={()=>androidMessage('checkUpdate')}>Buscar atualização</button></article></div>
 <details className="device-diagnostics"><summary>Testes e diagnóstico</summary><p>Confira a central de notificações. No teste agendado, minimize o app e aguarde 30 segundos.</p><div className="settings-actions"><button disabled={!device?.notifications} onClick={()=>deviceAction('testNotification')}>Testar agora</button><button disabled={!device?.notifications} onClick={()=>deviceAction('testScheduledNotification')}>Testar em 30 segundos</button></div>{device?.checkedAt&&<small>Última verificação: {new Date(device.checkedAt).toLocaleTimeString('pt-BR')}</small>}</details>
 <p className="device-feedback" role="status" aria-live="polite">{deviceNotice}</p>
 </>:<div className="device-web"><strong>Permissões no aplicativo Android</strong><p>Abra esta página no app para gerenciar notificações, horários precisos e biometria. Os lembretes por e-mail continuam independentes.</p></div>}</section>
 <section className="panel settings-panel"><div className="panel-title"><h3>Conta e ajuda</h3></div><div className="settings-actions"><button onClick={()=>{window.dispatchEvent(new Event('heroes-replay-tour'));}}>Rever primeiros passos</button><button className="red" onClick={onLogout}>Sair da conta</button></div></section></div>;
}
